### ISSUE TITLE
Allow collections to be created using TTL (time to live)

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#121] opened 2015-05-27 16:38 UTC
This is related to the https://github.com/lightblue-platform/lightblue-publish-hook and a desire to not keep events around definitely after they have been processed.

See also: http://docs.mongodb.org/manual/tutorial/expire-data/

**Comment by bserdar** [comment] 2015-08-14 04:45
Duplicate of #1

**Closed by bserdar** 2015-08-14 04:45 UTC
